# Generated by Django 4.1.4 on 2023-09-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name_plural': 'guides'},
        ),
    ]
