# Generated by Django 4.1.4 on 2023-09-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_university_options'),
        ('guide', '0003_alter_guide_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.university'),
        ),
    ]
