# Generated by Django 4.1.4 on 2023-09-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_options_alter_student_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='abcd', max_length=100),
            preserve_default=False,
        ),
    ]
