# Generated by Django 4.1.4 on 2023-09-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dissertation',
            table='dissertations',
        ),
    ]
