# Generated by Django 4.1.4 on 2023-09-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_alter_dissertation_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dissertation',
            options={'verbose_name_plural': 'PG Dissertations'},
        ),
    ]
