# Generated by Django 4.1.4 on 2023-09-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0003_alter_dissertation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
