# Generated by Django 4.1.4 on 2023-09-20 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dissertation', '0004_alter_dissertation_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='author_id',
            field=models.OneToOneField(default=1234, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
