# Generated by Django 4.1.4 on 2023-09-20 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dissertation', '0005_dissertation_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='author_id',
        ),
        migrations.AddField(
            model_name='dissertation',
            name='author_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
