# Generated by Django 4.1.4 on 2023-09-21 06:03

import dissertation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0006_remove_dissertation_author_id_dissertation_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='full_paper',
            field=models.FileField(blank=True, upload_to=dissertation.models.rename_papers),
        ),
    ]
