# Generated by Django 4.1.4 on 2023-09-23 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0007_alter_dissertation_full_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dissertation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
