# Generated by Django 4.1.4 on 2023-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0008_dissertation_created_at_dissertation_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='guide_feedback',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dissertation',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='university_feedback',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
